name: Daily Refresh

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    songs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        defaults:
            run:
                working-directory: ./generator
        steps:
            - name: Checkout
              uses: actions/checkout@v4
    
            - name: Setup Node
              uses: actions/setup-node@v4
    
            - name: Install dependencies
              run: npm install

            - name: Generate validation schema
              run: npx ts-to-zod ../schemas/songs.d.ts ./songs.zod.js
    
            - name: Generate database
              run: node ./songs.js

            - name: Commit changes
              run: |
                  cd ../
                  
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git add artifacts/
                  git diff --cached --quiet artifacts/ && exit 0
            
                  git commit -m "Update songs database"
                  git push
    art:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        defaults:
            run:
                working-directory: ./generator
        steps:
            - name: Checkout
              uses: actions/checkout@v4
    
            - name: Setup Node
              uses: actions/setup-node@v4
    
            - name: Install dependencies
              run: npm install

            - name: Generate validation schema
              run: npx ts-to-zod ../schemas/art.d.ts ./art.zod.js
    
            - name: Generate database
              run: node ./art.js

            - name: Commit changes
              run: |
                  cd ../
                  
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git add artifacts/
                  git diff --cached --quiet artifacts/ && exit 0
                             
                  git commit -m "Update art database"
                  git push
